### ISSUE TITLE
`inheritance.tree` не соответствует действительности

### ISSUE THREAD

**Issue by SolidKane** [mrmlnc/yellfy-pug-inheritance#22]
Я использую ваш плагин в таком формате:

```js
const gulp = require('gulp');
const gulpif = require('gulp-if');
const filter = require('gulp-filter');
const pugInheritance = require('yellfy-pug-inheritance');
const pug = require('gulp-pug');
const less = require('gulp-less');
const browserSync = require('browser-sync');
const rename = require('gulp-rename');

let pugInheritanceCache = {};

gulp.task('watch', () => {
  global.watch = true;

  gulp.watch(['tpl/**/*.pug'], gulp.series('templates'))
    .on('all', (event, filepath) => {
      global.changedTempalteFile = filepath.replace(/\\/g, '/');
    });
});

function pugFilter(file, inheritance) {
  const filepath = `tpl/${file.relative}`; 
  console.log(file.relative);
  const depend = inheritance.getDependencies(filepath);
  console.log(depend);
  if (inheritance.checkDependency(filepath, global.changedTempalteFile)) {
    console.log(`Compiling: ${filepath}`);
    return true;
  }
  return false;
}

gulp.task('templates', () => {
  return new Promise((resolve, reject) => {
    const changedFile = global.changedTempalteFile;
    const options = {
      changedFile,
      treeCache: pugInheritanceCache
    };

    pugInheritance.updateTree('tpl/', options).then((inheritance) => {
      // Save cache for secondary compilations
      pugInheritanceCache = inheritance.tree;

      return gulp.src('tpl/*.pug')
        .pipe(gulpif(global.watch, filter((file) => pugFilter(file, inheritance))))
        .pipe(pug({ pretty: true }))
        .pipe(gulp.dest('../../'))
        .on('end', resolve)
        .on('error', reject)
    });
  });
});
```

При компиляции шаблона консоль выдает такое дерево:

```
[21:30:23] Starting 'templates'...
cabinet.pug
[ 'tpl.pug', 'tpl/footer/pug/footer.pug', 'tpl/cabinet.pug' ]
index.pug
[ 'tpl.pug', 'tpl/footer/pug/footer.pug', 'tpl/index.pug' ]
news_list.pug
[ 'tpl.pug', 'tpl/footer/pug/footer.pug', 'tpl/news_list.pug' ]
orders_history.pug
[ 'tpl.pug',
  'tpl/footer/pug/footer.pug',
  'tpl/orders_history.pug' ]
order_creation.pug
[ 'tpl.pug',
  'tpl/footer/pug/footer.pug',
  'tpl/order_creation.pug' ]
payment.pug
[ 'tpl.pug', 'tpl/footer/pug/footer.pug', 'tpl/payment.pug' ]
post.pug
[ 'tpl.pug', 'tpl/footer/pug/footer.pug', 'tpl/post.pug' ]
product_card.pug
[ 'tpl.pug',
  'tpl/footer/pug/footer.pug',
  'tpl/product_card.pug' ]
product_list.pug
[ 'tpl.pug',
  'tpl/footer/pug/footer.pug',
  'tpl/product_list.pug' ]
registration.pug
[ 'tpl.pug',
  'tpl/footer/pug/footer.pug',
  'tpl/registration.pug' ]
registration_entity.pug
[ 'tpl.pug',
  'tpl/footer/pug/footer.pug',
  'tpl/registration_entity.pug' ]
test.pug
[ 'tpl.pug', 'tpl/common/test_cont_hed.pug', 'tpl/test.pug' ]
[21:30:23] Finished 'templates' after 250 ms
```

Это не отражает полного дерева зависимостей моего файла(пример, test.pug):

```jade
doctype html
html
  include common/test_cont.pug
  body
    include common/test_cont.pug
    include common/test_cont_hed.pug
```

Получается при изменений `include` мой шаблон в котором используется этот `include` не пересобирается.

В чем может быть причина?

**Comment by mrmlnc** [comment]
Похоже на то, что кеш не инвалидируется, если я правильно понял ваш комментарий. Скорее всего так оно и есть, но это возможно лишь в случае, когда вы изменяете в проекте сразу несколько файлов одновременно.

Есть возможность собрать тестовый репозиторий? Если нет, то опишите последовательность ваших действий (1,2,3...), чтобы я мог воспроизвести баг у себя.

**Comment by SolidKane** [comment]
У меня идет такая структура:

```
/tpl/
==index.pug
==cabinet.pug
...
==user.pug
```

И в каждом шаблоне идет `include common/pug/header.pug`, т.е. я понимаю так, что будет происходить рекомпиляция всех шаблонов, которые зависят от `header.pug`? Может в этом проблема и как ее решить?

**Comment by mrmlnc** [comment]
@SolidKane,

Компилироваться будут только те файлы, которые зависят от изменившегося файла. Например, если вы измените `head.pug` и от него зависят все файлы проекта, то к компиляции будут допущены все файлы. Если вы измерите файл `abc.pug` И от него зависит лишь файл `main.pug`, то скомпилирован будет только он. Но, если от файла `main.pug` зависят другие файлы, то они также будут скомпилированы.

**Comment by wangel13** [comment]
Ну тогда проблема в том, что дерево зависимостей не содержит необходимых файлов(от которых зависит данный файл). И ничего не пересобирается при изменений инклюда =(

**Comment by wangel13** [comment]
Вывод метода `nheritance.getDependencies(filepath);`
```
test.pug
[ 'tpl.pug', 'tpl/common/test_cont_hed.pug', 'tpl/test.pug' ]
```

Но в данном файле написано:

```jade
doctype html
html
  include common/test_cont.pug
  body
    include common/test_cont.pug
    include common/test_cont_hed.pug
```

В дереве нет `test_cont.pug`... 
И не понятно что означает `tpl.pug` в зависимостях..

**Comment by mrmlnc** [comment]
Древо может не содержать файлов только в том случае, если они были изменены без вотчера или находятся за пределами директории, которая указана как основная (в вашем случае `tpl`).

Если вы соберёте тестовый репозиторий, то будет замечательно и я смогу отследить ошибку, если нет, то придётся подождать до завтра.

**Comment by mrmlnc** [comment]
Хмм, действительно, что за `tpl.pug` 🦀

**Comment by SolidKane** [comment]
Тестовый репозиторий
https://github.com/SolidKane/gulp-yellfy-pug-inheritance-test

**Comment by mrmlnc** [comment]
Итак, `tpl.pug` появляется из-за пробела в конце `include ./bla/bla `. Я допустил ошибку в регулярке, которая привела к жадности выражения. Исправлено https://github.com/mrmlnc/yellfy-pug-inheritance/commit/efbfea031a10484f13ec57153268dcf8bafe3daa.

Но я не совсем понимаю остальное поведение. Как я понимаю ваш баг:

  1. Вы открываете файл, например, `tpl/catalog.pug` и сохраняете его:

   ```
Compiling: tpl/catalog.pug   // Корректно
deps:
[ 'tpl/common/pug/head.pug',
  'tpl/header/pug/header.pug',
  'tpl/catalog/pug/catalog.pug',
  'tpl/footer/pug/footer.pug',
  'tpl/catalog.pug' ]
```

  2. Затем вы меняете, например, `include catalog/pug/catalog.pug` на `include news/pug/news.pug`:

```
Compiling: tpl/catalog.pug   // Корректно
deps:
[ 'tpl/common/pug/head.pug',
  'tpl/header/pug/header.pug',
  'tpl/news/pug/news.pug',   // <----- Обновлённая зависимость
  'tpl/footer/pug/footer.pug',
  'tpl/catalog.pug' ]
```

  3. Затем вы меняете `head.pug` (т.е. все страницы компилируются):

```
Compiling: tpl/catalog.pug
deps:
[ 'tpl/common/pug/head.pug',
  'tpl/header/pug/header.pug',
  'tpl/news/pug/news.pug',
  'tpl/footer/pug/footer.pug',
  'tpl/catalog.pug' ]
Compiling: tpl/index.pug
deps:
[ 'tpl/common/pug/head.pug',
  'tpl/header/pug/header.pug',
  'tpl/home/pug/home.pug',
  'tpl/footer/pug/footer.pug',
  'tpl/index.pug' ]
Compiling: tpl/news.pug
deps:
[ 'tpl/common/pug/head.pug',
  'tpl/header/pug/header.pug',
  'tpl/news/pug/news.pug',
  'tpl/footer/pug/footer.pug',
  'tpl/news.pug' ]
```

**Comment by SolidKane** [comment]
@mrmlnc

**Comment by SolidKane** [comment]
@mrmlnc обновите npm? протестировать не терпится

**Comment by mrmlnc** [comment]
@SolidKane, да, я сейчас обновлю алгоритм отсева комментариев из второй версии этого пакета, раз уж обновлять пакет нужно :)

**Comment by mrmlnc** [comment]
@SolidKane готово, **1.1.1**. Если проблема до сих пор наблюдается, то напишите как вы её пошагово воспроизводите.

**Comment by SolidKane** [comment]
@mrmlnc обновляюсь :)

**Comment by SolidKane** [comment]
@mrmlnc спасибо за оперативность! все заработало :)

**Comment by mrmlnc** [comment]
Немного рекламы:

В свободное время работаю над второй версией, где будет существенно упрощён процесс включения плагина в окружение (практически, как включить Gulp-плагин) и максимальным охватом шаблонизаторов и CSS-препроцессоров (просто указываете RegExp и пакет сам обо всём позаботится).

**Comment by SolidKane** [comment]
@mrmlnc круто было бы добавить ко всему этому чуду livereload. сейчас голову ломаю как подружить все это с browserSync. Поделитесь советом по возможности

**Comment by mrmlnc** [comment]
@SolidKane, достаточно в вотчере добавить задачу:

https://github.com/mrmlnc/yellfy/blob/2.0.0/gulp/tasks/watch.js#L35-L40
