### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by Efimenko** [mrmlnc/yellfy-pug-inheritance#23]
При запуске вашего gulp example в консоль получаю следующее:

**[20:40:08] Starting 'default'...
[20:40:08] Starting 'templates'...
(node:5688) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Assignment to constant variable.
(node:5688) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.**

Это связано с самим node?

Node version 7.2.0
CLI version 1.2.2
Local version 4.0.0-alpha.2

**Comment by mrmlnc** [comment]
Для начала хорошо бы понять, какую версию Node.js вы используете?

**Comment by Efimenko** [comment]
обновил вопрос, описал версии

**Comment by mrmlnc** [comment]
Ох, это относится к:

```js
const pugInheritanceCache = {};
```

Попробуй заменить `const` на `let`. Когда обновлял документацию не  заметил, что `pugInheritanceCache` ниже присваивается значение.

**Comment by Efimenko** [comment]
Шикарно, спасибо.
