### ISSUE TITLE
Include внутри extend-шаблона 

### ISSUE THREAD

**Issue by natrey** [mrmlnc/yellfy-pug-inheritance#24]
Спасибо за пакет! Тоже сталкивалась с проблемой использования gulp-jade-inheritance, о которой вы  пишите в  [блоге](https://canonium.com/articles/pug-incremental-compiling).  
У меня все работает, кроме одного момента. Кейс похожий на issue #22.
Есть такой пример структуры:

- templates/
    - page.pug
    - header.pug
    - footer.pug
- catalog.pug
- news.pug

Шаблон page расширяется через extends в catalog.pug и news.pug. Внутри page include'ом добавляется header, footer. Если вносить изменения в include'ах, то в скомпиленных catalog.html, news.html изменения **не** подтягиваются. При этом если править page.pug, то изменения добавляются, все ок.
Добавила тестовый репозиторий https://github.com/iNata/yellfy-pug-inheritance-example 
Подскажите, как побороть этот момент?

**Comment by mrmlnc** [comment]
Привет, @iNata,

Я вчера обновил документацию примера для Gulp и заменил `const` на `let` для `pugInheritanceCache`, так как ранее не заметил этот момент.

Итак, после изменений, что я описал выше, я пытаюсь воспроизвести вашу проблему:

#### Изменяю `example/templates/footer.pug` и получаю:

```
Compiling: example/catalog.pug
Compiling: example/news.pug
```

#### Изменяю `example/templates/header.pug` и получаю:

```
Compiling: example/catalog.pug
Compiling: example/news.pug
```

#### Изменяю `example/templates/page.pug` и получаю:

```
Compiling: example/catalog.pug
Compiling: example/news.pug
```

#### Изменяю `example/catalog.pug` и получаю:

```
Compiling: example/catalog.pug
```

#### Изменяю `example/news.pug` и получаю:

```
Compiling: example/news.pug
```

Вроде бы всё корректно. Дайте мне знать, если проблема наблюдается до сих пор.

**Comment by natrey** [comment]
@mrmlnc,
внесла правки в gulpfile, но при изменении header/footer изменения не подтягиваются все равно.
Добавила gulp-debug в конфиг, вроде как после pugFilter изменения не компилятся.

![gulpfile_scr](https://cloud.githubusercontent.com/assets/5160375/20764153/f4b24a72-b73d-11e6-97fd-e0ddb65e2f7b.jpg)

**Comment by mrmlnc** [comment]
Интересненько 🐼 

Что выводится в консоль, если изменить `pugFilter` следующим образом:

```js
// Filter for files
function pugFilter(file, inheritance) {
  const filepath = `${pugDirectory}/${file.relative}`;
  console.log(filepath);  // <-------------------------- here
  console.log(inheritance.getDependencies(filepath)); // <---------------------- here
  if (inheritance.checkDependency(filepath, global.changedTemplateFile)) {
    console.log(`Compiling: ${filepath}`);
    return true;
  }
  return false;
}
```

И парочка вопросов, чтобы я мог попробовать воспроизвести ситуацию у себя:

  1. OS?
  2. Node.js version?

**Comment by natrey** [comment]
Обновила версию node.js с 5.5.0 до 6.9.1, но не помогло, эх  :unamused:
Да, windows 7.
Добавила логи в pugFilter,  при изменении page.pug соот. выводится: 
```
[12:23:04] Starting 'templates'...
[12:23:04] src example\catalog.pug
example/catalog.pug
[ 'example/templates/page.pug', 'example/catalog.pug' ]
Compiling: example/catalog.pug
[12:23:05] pug example\catalog.html
[12:23:05] src example\news.pug
example/news.pug
[ 'example/templates/page.pug', 'example/news.pug' ]
Compiling: example/news.pug
[12:23:05] pug example\news.html
[12:23:05] src 2 items
[12:23:05] pug 2 items
[12:23:05] Finished 'templates' after 431 ms
```

при изменении header.pug/footer.pug тоже самое, но до компиляции не доходит:
```
[12:23:14] Starting 'templates'...
[12:23:14] src example\catalog.pug
example/catalog.pug
[ 'example/templates/page.pug', 'example/catalog.pug' ]
[12:23:14] src example\news.pug
example/news.pug
[ 'example/templates/page.pug', 'example/news.pug' ]
[12:23:14] src 2 items
[12:23:14] pug 0 items
[12:23:14] Finished 'templates' after 23 ms
```

**Comment by mrmlnc** [comment]
Подтверждено.

Если запускать `gulp watch` из WebStorm, то зависимости для `page.pug` не находятся.

P.S.: Временное решение: попробовать запустить `gulp watch` из консоли, а не из редактора. Вроде как должно работать.

**Comment by mrmlnc** [comment]
Я не мог воспроизвести проблему, потому что на основной машине у меня Git автоматом меняет CRLF на LF при `git clone`.

Опубликовал версию `1.1.3`, в которой должна быть исправлена ваша проблема.

Если проблема наблюдается до сих пор, то я снова открою этот вопрос. Извиняюсь за доставленные неудобства 🐼

**Comment by natrey** [comment]
Ура-ура! Версия `1.1.3` работает! Спасибо большое  :raised_hands:
