### ISSUE TITLE
Не всегда срабатывает

### ISSUE THREAD

**Issue by jedybeavis** [mrmlnc/yellfy-pug-inheritance#25]
Gulp - 
CLI version 1.2.2
Local version 4.0.0-alpha.2

Node
v6.9.1

Странно, но есть некоторые файлы которые в inlude они не срабатывают, а некоторые срабатывают.
К примеру у меня есть файл Index.pug в нем есть блоки с папки index/blocA.pug, когда я его меняю и сохраняю происходит то что написано в терминал. Он вызывает Pug но ничего не делает.
![screenhttp-restart 2016-12-01 11 33 38](https://cloud.githubusercontent.com/assets/736017/20788656/5b5f42b2-b7ba-11e6-9fe6-8d3011b07ba4.png)

И еще один вопрос, у меня стоит browserSync. Наверно когда много файлов которые он собирает браузер быстрее перегружается чем соберет тот файл который я редактировал. Посоветуйте как это решить.

В целом спасибо за плагин!

**Comment by mrmlnc** [comment]
Небольшое уточнение по мотивам #24:

Если вы запускаете `gulp watch` из консоли, а не из редактора, то ошибка наблюдается?

Также, проблема наблюдается после обновления до версии `1.1.3`?

**Comment by jedybeavis** [comment]
Да через терминал так-же, и только что обновил до 1.1.3 но все работает так-же (

**Comment by mrmlnc** [comment]
Увы, не могу воспроизвести у себя ни на Windows 10 и Windows 8.1, ни на Manjaro и macOS Sierra.

Везде установлен Atom 1.12.6 + gulp-control 0.5.0.

Есть возможность поделиться вашим окружением здесь или на `dmalinochkin@rambler.ru`? Если есть время, то можно собрать тестовый репозиторий.

**Comment by jedybeavis** [comment]
Отправил на почту но могу и тестовый создать репозиторий.

**Comment by mrmlnc** [comment]
Подтверждено. 

Ошибка в новом алгоритме пропуска комментариев.

**Comment by mrmlnc** [comment]
Опубликовал версию `1.1.4`, в которой должна быть исправлена ваша проблема.

Если проблема наблюдается до сих пор, то я снова открою этот вопрос. Извиняюсь за доставленные неудобства 🐼

#HappyCoding

**Comment by jedybeavis** [comment]
Спасибо все работает!
